os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: '9'
      platform: x64
      msvs_toolset: 12
    - nodejs_version: '8'
      platform: x64
      msvs_toolset: 12
    - nodejs_version: '6'
      platform: x64
      msvs_toolset: 12
    - nodejs_version: '4'
      platform: x64
      msvs_toolset: 12

  npm_config_arch: x64

platform: x64

configuration: Release

skip_commits:
  files:
    - docs/*
    - Dockerfile
    - travis.yml
    - '**/*.html'
    - '*.md'

init:
  - cmd: node --version
  - cmd: npm --version

  - ps: Install-Product node $env:nodejs_version
  - cmd: node --version
  - cmd: npm --version

install:
  # Install gnats
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v1.0.2/gnatsd-v1.0.2-windows-386.zip
  - 7z e gnatsd-v1.0.2-windows-386.zip gnatsd.exe -r -oc:\projects\hemera\build
  - cmd: set PATH=%PATH%;C:\projects\hemera\build

  - npm run setup
  - npm run test

build: off
