language: node_js
sudo: false

node_js:
  - "4"
  - "5"
  - "6"

before_install:
  - apt-get install build-essential checkinstall
  - apt-get install libkrb5-dev
  - apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

before_script:
  - mkdir -p gnatsd
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.7.2/gnatsd-v0.7.2-linux-amd64.tar.gz -qO - | tar -zxvC gnatsd/

after_success:
  - npm run coveralls