language: node_js
sudo: true

node_js:
  - "4"
  - "5"
  - "6"

script:
  - npm run setup && npm run ci

env:
  - ARANGODB_VERSION=3.1 ARANGO_VERSION=30100
  
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash

before_script:
  - mkdir -p gnatsd
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.7.2/gnatsd-v0.7.2-linux-amd64.tar.gz -qO - | tar -zxvC gnatsd/

after_script:
  - kill -9 $(pgrep arangod)

after_success:
  - kill -9 $(pgrep arangod)