language: node_js
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
node_js:
  - "4"
  - "5"
  - "6"

script:
  - npm run setup && npm run ci

env:
  - ARANGODB_VERSION=3.1 ARANGO_VERSION=30100
  
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash

before_script:
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v0.9.6-linux-amd64 gnatsd

after_script:
  - kill -9 $(pgrep arangod)